---
- hosts: all
  become: true
  roles:
    - role: willshersystems.sshd

  handlers:

    - name: start ntp
      service:
        name: ntpd
        state: started
        enabled: true

  pre_tasks:

    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - bash-completion
        - curl
        - git
        - htop
        - mlocate
        - python-pip
        - screen
        - vim

    - name: remove packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - firewalld
        - firewalld-filesystem

  tasks:

    - name: set selinux to permissive
      selinux:
        state: permissive
        policy: targeted

    - name: install ntp
      yum:
        name: ntp
        state: present
      notify:
        - start ntp

    - name: add cloudstack repository
      yum_repository:
        name: cloudstack
        baseurl: http://cloudstack.apt-get.eu/centos/7/4.11/
        enabled: true
        gpgcheck: no

