---
- hosts: all
  become: true
  tasks:
    - name: enable php7.2 repository
      command: 'yum-config-manager --enable remi-72'

    - name: install webserver packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - nginx
        - php
        - php-mysql
        - php-intl
        - php-xml
        - php-pecl-zip

    - name: import mariadb role
      import_role:
        name: bertvv.mariadb
      vars:
        mariadb_databases:
          - name: wordpress
        mariadb_root_password: insecure
        mariadb_users:
          - name: wordpress
            password: wordpress
            priv: '*.*:ALL,GRANT'

    - name: create mysql client config for root
      copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user=root
          password=insecure

    - name: enable acmetool repository
      yum_repository:
        name: acmetool
        baseurl: https://copr-be.cloud.fedoraproject.org/results/hlandau/acmetool/epel-7-$basearch/
        description: Copr repo for acmetool owned by hlandau
        enabled: yes
        gpgkey: https://copr-be.cloud.fedoraproject.org/results/hlandau/acmetool/pubkey.gpg

    - name: install acmetool
      yum:
        name: acmetool
        state: present

    - name: copy httpd wordpress config
      command: cp /vagrant/templates/etc--httpd--conf.d--wordpress.conf /etc/httpd/conf.d/wordpress.conf

    - name: copy wordpress config
      command: cp /vagrant/templates/var--www--html--htdocs--wordpress--public--wp-config.php /var/www/html/htdocs/wordpress/public/wp-config.php

    - name: restart httpd
      service:
        name: httpd
        state: restarted

