---
- hosts: all
  become: true
  roles:
    - role: willshersystems.sshd
  tasks:

    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - git
        - htop
        - httpd
        - php
        - vim

    - name: remove packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - firewalld
        - firewalld-filesystem
        - NetworkManager
        - Networkmanager-libnm
        - NetworkManager-team
        - NetworkManager-tui
        - NetworkManager-wifi

