---
docker_repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
docker_repo_key: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
docker_package_string: "{{ docker_package }}{{ (docker_version == 'latest') | ternary('', '={}'.format(docker_version)) }}"
