---
docker_repo: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/docker-ce.repo"
docker_package_string: "{{ docker_package }}{{ (docker_version == 'latest') | ternary('', '-{}'.format(docker_version)) }}"
