---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: install dependencies
      yum:
        name: net-tools
        state: present
  roles:
    - role: ansible-docker
      docker_daemon_config:
        live-restore: true
        storage-driver: overlay2
        storage-opts:
          - 'overlay2.override_kernel_check=true'
      docker_remote: true
