---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  # - name: debian-8
  #   box: debian/jessie64
  - name: ubuntu-1604
    box: ubuntu/xenial64
provisioner:
  name: ansible
  env:
    MOLECULE_DEBUG: '1'
  lint:
    name: ansible-lint
scenario:
  name: debian
verifier:
  name: testinfra
  lint:
    name: flake8
