---
- hosts: all
  become: true
  roles:
    - role: bertvv.mariadb
    - role: willshersystems.sshd
  tasks:

    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - bash-completion
        - curl
        - git
        - htop
        - libselinux-python
        - mlocate
        - mosh
        - screen
        - vim

    - name: remove packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - firewalld
        - firewalld-filesystem
