---
- name: include distribution variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: include tasks for RedHat like distributions
  include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: include tasks for Debian like distributions
  include: debian.yml
  when: ansible_os_family == 'Debian'

- name: add users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"

- name: create docker configuration directory
  file:
    dest: /etc/docker
    state: directory

- name: configure docker daemon
  template:
    dest: /etc/docker/daemon.json
    src: daemon.json.j2
  notify:
    - reload docker daemon
    - restart docker daemon
  when: docker_daemon_config != {}

- name: create docker systemd drop-in directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: configure docker remote socket
  template:
    dest: /etc/systemd/system/docker.service.d/docker.conf
    src: docker.socket.j2
  notify:
    - reload daemons
    - reload docker daemon
    - restart docker daemon
  when: docker_remote

- name: enable docker daemon
  service:
    name: "{{ docker_daemon }}"
    enabled: true
  when: docker_enabled

- name: start docker daemon
  service:
    name: "{{ docker_daemon }}"
    state: started
  when: docker_started
